### ISSUE TITLE
UI Enhancements

### ISSUE THREAD

**Issue by vanshikapandey** [yashrajnayak/connecticut#5]
Hello Yashraj, 
I was part of GitTogether event that you recently hosted in Bengaluru. You introduced us with Connecticut there and I wis to contribute to it.

I wanted to work on the following features:

- Enhancing the Grid
- Adding more styles on the main screen
- Trying to add dark side

**Comment by yashrajnayak** [comment]
HI Vanshika, sure please feel free to fork and raise a PR after implementing these changes. btw we already have dark mode in the Connecticut app.

**Comment by yashrajnayak** [comment]
@vanshikapandey Please feel free to fork and raise a PR after implementing these changes. We already have dark mode.
